ARG BASE=nvidia/cuda:11.8.0-base-ubuntu22.04
FROM ${BASE}

# 设置非交互模式，避免 tzdata 卡死
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# ---- SYS Dependencies + Python 3.11 ----
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        gcc g++ make \
        python3.10 python3.10-venv python3.10-dev python3.10-distutils \
        espeak-ng libsndfile1-dev curl && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.11 python3.11-dev python3.11-venv && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
    rm -rf /var/lib/apt/lists/*

# ---- Python 库 ----
RUN pip3 install --no-cache-dir llvmlite --ignore-installed
RUN pip3 install --no-cache-dir torch torchaudio --extra-index-url https://download.pytorch.org/whl/cu118
RUN pip3 install --no-cache-dir "transformers==4.36.0"

# 删除冲突的系统包
RUN apt-get remove -y python3-blinker || true

# 保证 pip 装 blinker 新版本
RUN pip3 install --upgrade --ignore-installed blinker

# Copy TTS repository contents:
WORKDIR /root
COPY . /root

RUN make install

ENTRYPOINT ["tts"]
CMD ["--help"]
